# Generated by Django 5.2.6 on 2025-09-06 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news_project.category'),
            preserve_default=False,
        ),
    ]
